import { ethers } from 'ethers'
import fs from 'fs'
import path from 'path'
import { ARC_CONTRACTS, ARC_TESTNET } from '../constants/arc'

function randomBase64(bytes = 32) {
  return Buffer.from(ethers.randomBytes(bytes)).toString('base64')
}

function randomHex(bytes = 32) {
  return ethers.hexlify(ethers.randomBytes(bytes)).slice(2)
}

async function main() {
  console.log('\nGenerating ArcPredict wallets...\n')

  const deployer = ethers.Wallet.createRandom()
  const agent = ethers.Wallet.createRandom()
  const generatedAt = new Date().toISOString()

  console.log('Deployer wallet generated')
  console.log('   Address: ', deployer.address)
  console.log(`   Fund at:  ${ARC_TESTNET.faucetUrl} (select Arc Testnet, request USDC)\n`)

  console.log('Agent wallet generated')
  console.log('   Address: ', agent.address)
  console.log(`   Fund at:  ${ARC_TESTNET.faucetUrl} (select Arc Testnet, request USDC)\n`)

  const envContent = `# =============================================================
# ArcPredict - Environment Variables
# Generated by: pnpm setup (${generatedAt})
# NEVER commit this file to version control.
# =============================================================

# -- Arc Testnet ------------------------------------------------
# Source: https://docs.arc.io/arc/references/rpc-endpoints
NEXT_PUBLIC_ARC_RPC_URL=${ARC_TESTNET.rpcUrl}
NEXT_PUBLIC_ARC_WS_URL=${ARC_TESTNET.wsUrl}
NEXT_PUBLIC_ARC_CHAIN_ID=${ARC_TESTNET.chainId}
NEXT_PUBLIC_ARC_EXPLORER=${ARC_TESTNET.explorerUrl}

# -- Deployer Wallet (AUTO-GENERATED - DO NOT EDIT) ------------
# Fund this address with testnet USDC before deploying:
# ${ARC_TESTNET.faucetUrl}
DEPLOYER_ADDRESS=${deployer.address}
DEPLOYER_PRIVATE_KEY=${deployer.privateKey}
DEPLOYER_MNEMONIC="${deployer.mnemonic?.phrase ?? ''}"

# -- Agent Wallet (AUTO-GENERATED - DO NOT EDIT) ---------------
# Fund this address with testnet USDC before running the agent:
# ${ARC_TESTNET.faucetUrl}
AGENT_ADDRESS=${agent.address}
AGENT_PRIVATE_KEY=${agent.privateKey}
AGENT_MNEMONIC="${agent.mnemonic?.phrase ?? ''}"

# -- Arc Contract Addresses (testnet) --------------------------
# Source: https://docs.arc.io/arc/references/contract-addresses
NEXT_PUBLIC_USDC_ADDRESS=${ARC_CONTRACTS.USDC}
NEXT_PUBLIC_EURC_ADDRESS=${ARC_CONTRACTS.EURC}
NEXT_PUBLIC_USYC_ADDRESS=${ARC_CONTRACTS.USYC}
NEXT_PUBLIC_CCTP_TOKEN_MESSENGER=${ARC_CONTRACTS.CCTP_TOKEN_MESSENGER}
NEXT_PUBLIC_CCTP_MESSAGE_TRANSMITTER=${ARC_CONTRACTS.CCTP_MESSAGE_TRANSMITTER}
NEXT_PUBLIC_CCTP_ARC_DOMAIN=${ARC_CONTRACTS.CCTP_ARC_DOMAIN}
NEXT_PUBLIC_GATEWAY=${ARC_CONTRACTS.GATEWAY}
NEXT_PUBLIC_MULTICALL3=${ARC_CONTRACTS.MULTICALL3}
NEXT_PUBLIC_PERMIT2=${ARC_CONTRACTS.PERMIT2}

# -- ArcPredict Deployed Contracts (filled by Deploy.s.sol) ----
NEXT_PUBLIC_MARKET_FACTORY=
NEXT_PUBLIC_CONDITIONAL_TOKEN=
NEXT_PUBLIC_CPMM=
NEXT_PUBLIC_ORDER_BOOK=
NEXT_PUBLIC_ORACLE_RESOLVER=
NEXT_PUBLIC_DISPUTE_MODULE=
NEXT_PUBLIC_TREASURY_VAULT=

# -- Supabase ---------------------------------------------------
# Get from: https://supabase.com/dashboard -> Project Settings -> API
NEXT_PUBLIC_SUPABASE_URL=
NEXT_PUBLIC_SUPABASE_ANON_KEY=
SUPABASE_SERVICE_ROLE_KEY=

# -- LI.FI ------------------------------------------------------
# Get from: https://portal.li.fi (API key optional for testnet)
NEXT_PUBLIC_LIFI_API_KEY=
NEXT_PUBLIC_LIFI_INTEGRATOR=arcpredict

# -- Chainlink --------------------------------------------------
# Verify feed addresses at: https://docs.chain.link/data-feeds/price-feeds/addresses
NEXT_PUBLIC_CHAINLINK_BTC_USD=
NEXT_PUBLIC_CHAINLINK_ETH_USD=

# -- App / Agent -----------------------------------------------
NEXT_PUBLIC_APP_URL=http://localhost:3000
NEXTAUTH_SECRET=${randomBase64(32)}
AGENT_CRON_SECRET=${randomHex(32)}

# -- Fairblock --------------------------------------------------
# Fairblock docs currently list Arc as 1244 while Arc docs list 5042002.
# Keep overrideable until Fairblock support confirms Arc Testnet mapping.
FAIRBLOCK_CHAIN_ID=1244
`

  const envPath = path.resolve(process.cwd(), '.env.local')
  fs.writeFileSync(envPath, envContent, { flag: 'w' })

  console.log('Written .env.local to', envPath)
  console.log('\nNEXT STEPS:')
  console.log(`   1. Fund DEPLOYER wallet at ${ARC_TESTNET.faucetUrl}`)
  console.log('      Address:', deployer.address)
  console.log(`   2. Fund AGENT wallet at ${ARC_TESTNET.faucetUrl}`)
  console.log('      Address:', agent.address)
  console.log('   3. Fill the remaining empty env variables in .env.local')
  console.log('   4. Run: pnpm contracts:deploy')
  console.log('   5. Run: pnpm dev\n')
}

main().catch((error) => {
  console.error(error)
  process.exit(1)
})
